version: '3.7'

services:
  db:
    container_name: "db"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "something"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
networks:
  default:
volumes:
  mysql_data:
